-- =================================================================
-- DMT EDUCATION SYSTEM DATABASE - SQL SERVER SCHEMA
-- =================================================================
--
-- FILE NÀY TẠO CẤU TRÚC DATABASE CHO SQL SERVER
-- =================================================================
-- HƯỚNG DẪN CÀI ĐẶT:
-- 1. Tạo database trước (nếu chưa có):
--    CREATE DATABASE DMT_EDUCATION_SYSTEM;
-- 2. Chạy file này trong database đã tạo
-- =================================================================

-- Kiểm tra và tạo database nếu chưa tồn tại
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'DMT_EDUCATION_SYSTEM')
BEGIN
    CREATE DATABASE DMT_EDUCATION_SYSTEM;
END
GO

USE DMT_EDUCATION_SYSTEM;
GO

-- Xóa các bảng cũ nếu tồn tại (để tránh conflict khi chạy lại)
IF OBJECT_ID('BACKUP_HISTORY', 'U') IS NOT NULL DROP TABLE BACKUP_HISTORY;
IF OBJECT_ID('SYSTEM_SETTINGS', 'U') IS NOT NULL DROP TABLE SYSTEM_SETTINGS;
IF OBJECT_ID('ACTIVITY_LOGS', 'U') IS NOT NULL DROP TABLE ACTIVITY_LOGS;
IF OBJECT_ID('NOTIFICATIONS', 'U') IS NOT NULL DROP TABLE NOTIFICATIONS;
IF OBJECT_ID('NEWS', 'U') IS NOT NULL DROP TABLE NEWS;
IF OBJECT_ID('SURVEY_RESPONSES', 'U') IS NOT NULL DROP TABLE SURVEY_RESPONSES;
IF OBJECT_ID('SURVEY_QUESTIONS', 'U') IS NOT NULL DROP TABLE SURVEY_QUESTIONS;
IF OBJECT_ID('SURVEYS', 'U') IS NOT NULL DROP TABLE SURVEYS;
IF OBJECT_ID('PAYMENTS', 'U') IS NOT NULL DROP TABLE PAYMENTS;
IF OBJECT_ID('MATERIALS', 'U') IS NOT NULL DROP TABLE MATERIALS;
IF OBJECT_ID('GRADES', 'U') IS NOT NULL DROP TABLE GRADES;
IF OBJECT_ID('SUBMISSIONS', 'U') IS NOT NULL DROP TABLE SUBMISSIONS;
IF OBJECT_ID('ASSIGNMENTS', 'U') IS NOT NULL DROP TABLE ASSIGNMENTS;
IF OBJECT_ID('ATTENDANCE', 'U') IS NOT NULL DROP TABLE ATTENDANCE;
IF OBJECT_ID('ENROLLMENTS', 'U') IS NOT NULL DROP TABLE ENROLLMENTS;
IF OBJECT_ID('CLASS_SESSIONS', 'U') IS NOT NULL DROP TABLE CLASS_SESSIONS;
IF OBJECT_ID('CLASSES', 'U') IS NOT NULL DROP TABLE CLASSES;
IF OBJECT_ID('COURSES', 'U') IS NOT NULL DROP TABLE COURSES;
IF OBJECT_ID('SUBJECTS', 'U') IS NOT NULL DROP TABLE SUBJECTS;
IF OBJECT_ID('STAFF', 'U') IS NOT NULL DROP TABLE STAFF;
IF OBJECT_ID('TEACHERS', 'U') IS NOT NULL DROP TABLE TEACHERS;
IF OBJECT_ID('STUDENTS', 'U') IS NOT NULL DROP TABLE STUDENTS;
IF OBJECT_ID('USERS', 'U') IS NOT NULL DROP TABLE USERS;
IF OBJECT_ID('ROLES', 'U') IS NOT NULL DROP TABLE ROLES;
GO

-- =================================================================
-- BẢNG CORE - QUẢN LÝ NGƯỜI DÙNG
-- =================================================================

CREATE TABLE ROLES (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  CODE VARCHAR(50) UNIQUE NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION NVARCHAR(MAX),
  CREATED_AT DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE USERS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  ROLE_ID INT NOT NULL,
  EMAIL VARCHAR(255) UNIQUE NOT NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  FULL_NAME NVARCHAR(255) NOT NULL,
  PHONE VARCHAR(20),
  ADDRESS NVARCHAR(MAX),
  BIRTH_DATE DATE,
  AVATAR_URL VARCHAR(500),
  STATUS BIT DEFAULT 1,
  LAST_LOGIN_AT DATETIME2,
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  UPDATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_USERS_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

CREATE TABLE STUDENTS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  USER_ID INT UNIQUE NOT NULL,
  STUDENT_CODE VARCHAR(50) UNIQUE,
  SCHOOL_LEVEL VARCHAR(50), -- ELEMENTARY, MIDDLE_SCHOOL, HIGH_SCHOOL
  PARENT_NAME NVARCHAR(255),
  PARENT_PHONE VARCHAR(20),
  PARENT_EMAIL VARCHAR(255),
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_STUDENTS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE TEACHERS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  USER_ID INT UNIQUE NOT NULL,
  TEACHER_CODE VARCHAR(50) UNIQUE,
  MAIN_SUBJECT_ID INT,
  YEARS_EXPERIENCE INT DEFAULT 0,
  DEGREE NVARCHAR(255),
  SPECIALIZATION NVARCHAR(255),
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_TEACHERS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE STAFF (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  USER_ID INT UNIQUE NOT NULL,
  STAFF_CODE VARCHAR(50) UNIQUE,
  DEPARTMENT NVARCHAR(120),
  POSITION NVARCHAR(120),
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_STAFF_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- =================================================================
-- BẢNG QUẢN LÝ HỌC VỤ
-- =================================================================

CREATE TABLE SUBJECTS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  NAME NVARCHAR(120) NOT NULL,
  CODE VARCHAR(50) UNIQUE NOT NULL,
  DESCRIPTION NVARCHAR(MAX),
  IS_ACTIVE BIT DEFAULT 1,
  CREATED_AT DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE COURSES (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  SUBJECT_ID INT NOT NULL,
  CODE VARCHAR(50) UNIQUE NOT NULL,
  NAME NVARCHAR(255) NOT NULL,
  DESCRIPTION NVARCHAR(MAX),
  DURATION_WEEKS INT DEFAULT 12,
  TOTAL_SESSIONS INT DEFAULT 24,
  PRICE DECIMAL(12,2),
  LEVEL VARCHAR(20) DEFAULT 'BEGINNER', -- BEGINNER, INTERMEDIATE, ADVANCED
  IS_ACTIVE BIT DEFAULT 1,
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_COURSES_SUBJECTS FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(ID)
);

CREATE TABLE CLASSES (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  COURSE_ID INT NOT NULL,
  CODE VARCHAR(50) UNIQUE NOT NULL,
  NAME NVARCHAR(255) NOT NULL,
  TEACHER_ID INT NOT NULL,
  CAPACITY INT DEFAULT 25,
  CURRENT_STUDENTS INT DEFAULT 0,
  START_DATE DATE,
  END_DATE DATE,
  SCHEDULE_DAYS VARCHAR(50), -- "MONDAY,WEDNESDAY,FRIDAY"
  SCHEDULE_TIME VARCHAR(20), -- "18:00-20:00"
  CLASSROOM NVARCHAR(100),
  STATUS VARCHAR(20) DEFAULT 'PLANNING', -- PLANNING, ACTIVE, COMPLETED, CANCELLED
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_CLASSES_COURSES FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID),
  CONSTRAINT FK_CLASSES_TEACHERS FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(ID)
);

CREATE TABLE CLASS_SESSIONS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  CLASS_ID INT NOT NULL,
  SESSION_NUMBER INT NOT NULL,
  TITLE NVARCHAR(255),
  SESSION_DATE DATE NOT NULL,
  START_TIME TIME NOT NULL,
  END_TIME TIME NOT NULL,
  CONTENT NVARCHAR(MAX),
  HOMEWORK NVARCHAR(MAX),
  STATUS VARCHAR(20) DEFAULT 'SCHEDULED', -- SCHEDULED, COMPLETED, CANCELLED
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_CLASS_SESSIONS_CLASSES FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID) ON DELETE CASCADE
);

-- =================================================================
-- BẢNG QUẢN LÝ ĐĂNG KÝ & ĐIỂM DANH
-- =================================================================

CREATE TABLE ENROLLMENTS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  CLASS_ID INT NOT NULL,
  STUDENT_ID INT NOT NULL,
  ENROLLMENT_DATE DATE DEFAULT CAST(GETDATE() AS DATE),
  STATUS VARCHAR(20) DEFAULT 'ACTIVE', -- ACTIVE, COMPLETED, DROPPED, SUSPENDED
  PAYMENT_STATUS VARCHAR(20) DEFAULT 'PENDING', -- PENDING, PAID, PARTIAL, OVERDUE
  TOTAL_FEE DECIMAL(12,2),
  PAID_AMOUNT DECIMAL(12,2) DEFAULT 0,
  DISCOUNT_PERCENT DECIMAL(5,2) DEFAULT 0,
  NOTES NVARCHAR(MAX),
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_ENROLLMENTS_CLASSES FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID),
  CONSTRAINT FK_ENROLLMENTS_STUDENTS FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID)
);

CREATE TABLE ATTENDANCE (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  SESSION_ID INT NOT NULL,
  ENROLLMENT_ID INT NOT NULL,
  STATUS VARCHAR(20) DEFAULT 'ABSENT', -- PRESENT, ABSENT, LATE, EXCUSED
  CHECK_IN_TIME DATETIME2,
  NOTES NVARCHAR(MAX),
  MARKED_BY INT, -- TEACHER/STAFF WHO MARKED
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_ATTENDANCE_SESSIONS FOREIGN KEY (SESSION_ID) REFERENCES CLASS_SESSIONS(ID),
  CONSTRAINT FK_ATTENDANCE_ENROLLMENTS FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENTS(ID),
  CONSTRAINT FK_ATTENDANCE_MARKED_BY FOREIGN KEY (MARKED_BY) REFERENCES USERS(ID)
);

-- =================================================================
-- BẢNG QUẢN LÝ BÀI TẬP & ĐIỂM SỐ
-- =================================================================

CREATE TABLE ASSIGNMENTS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  CLASS_ID INT NOT NULL,
  TITLE NVARCHAR(255) NOT NULL,
  DESCRIPTION NVARCHAR(MAX),
  DUE_DATE DATE,
  MAX_SCORE DECIMAL(6,2) DEFAULT 100,
  ASSIGNMENT_TYPE VARCHAR(30) DEFAULT 'HOMEWORK', -- HOMEWORK, QUIZ, EXAM, PROJECT
  CREATED_BY INT NOT NULL,
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_ASSIGNMENTS_CLASSES FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID),
  CONSTRAINT FK_ASSIGNMENTS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

CREATE TABLE SUBMISSIONS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  ASSIGNMENT_ID INT NOT NULL,
  STUDENT_ID INT NOT NULL,
  SUBMISSION_DATE DATETIME2 DEFAULT GETDATE(),
  CONTENT NVARCHAR(MAX),
  ATTACHMENT_URL VARCHAR(500),
  SCORE DECIMAL(6,2),
  FEEDBACK NVARCHAR(MAX),
  GRADED_BY INT,
  GRADED_AT DATETIME2,
  STATUS VARCHAR(20) DEFAULT 'SUBMITTED', -- SUBMITTED, GRADED, LATE, MISSING
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_SUBMISSIONS_ASSIGNMENTS FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENTS(ID),
  CONSTRAINT FK_SUBMISSIONS_STUDENTS FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID),
  CONSTRAINT FK_SUBMISSIONS_GRADED_BY FOREIGN KEY (GRADED_BY) REFERENCES USERS(ID)
);

CREATE TABLE GRADES (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  ENROLLMENT_ID INT NOT NULL,
  GRADE_TYPE VARCHAR(30) DEFAULT 'MIDTERM', -- MIDTERM, FINAL, ASSIGNMENT, OVERALL
  SCORE DECIMAL(6,2),
  MAX_SCORE DECIMAL(6,2) DEFAULT 100,
  WEIGHT DECIMAL(5,2), -- PHẦN TRĂM TRỌNG SỐ
  NOTES NVARCHAR(MAX),
  GRADED_BY INT NOT NULL,
  GRADED_AT DATETIME2 DEFAULT GETDATE(),
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_GRADES_ENROLLMENTS FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENTS(ID),
  CONSTRAINT FK_GRADES_GRADED_BY FOREIGN KEY (GRADED_BY) REFERENCES USERS(ID)
);

-- =================================================================
-- BẢNG QUẢN LÝ TÀI LIỆU HỌC TẬP
-- =================================================================

CREATE TABLE MATERIALS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  CLASS_ID INT NOT NULL,
  TITLE NVARCHAR(255) NOT NULL,
  DESCRIPTION NVARCHAR(MAX),
  FILE_URL VARCHAR(500),
  FILE_TYPE VARCHAR(50),
  FILE_SIZE BIGINT,
  UPLOADED_BY INT NOT NULL,
  IS_PUBLIC BIT DEFAULT 0,
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_MATERIALS_CLASSES FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID),
  CONSTRAINT FK_MATERIALS_UPLOADED_BY FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(ID)
);

-- =================================================================
-- BẢNG QUẢN LÝ THANH TOÁN
-- =================================================================

CREATE TABLE PAYMENTS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  PAYMENT_CODE VARCHAR(50) UNIQUE,
  ENROLLMENT_ID INT NOT NULL,
  AMOUNT DECIMAL(12,2) NOT NULL,
  PAYMENT_DATE DATE DEFAULT CAST(GETDATE() AS DATE),
  PAYMENT_METHOD VARCHAR(50), -- CASH, BANK_TRANSFER, CREDIT_CARD, E_WALLET
  TRANSACTION_ID VARCHAR(255),
  STATUS VARCHAR(20) DEFAULT 'COMPLETED', -- PENDING, COMPLETED, FAILED, REFUNDED
  RECEIPT_NUMBER VARCHAR(50),
  DESCRIPTION NVARCHAR(500),
  PAYMENT_DETAILS NVARCHAR(500),
  NOTES NVARCHAR(MAX),
  PROCESSED_BY INT,
  CREATED_BY VARCHAR(100),
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  UPDATED_AT DATETIME2,
  CONSTRAINT FK_PAYMENTS_ENROLLMENTS FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENTS(ID),
  CONSTRAINT FK_PAYMENTS_PROCESSED_BY FOREIGN KEY (PROCESSED_BY) REFERENCES USERS(ID)
);

-- =================================================================
-- BẢNG KHẢO SÁT & ĐÁNH GIÁ
-- =================================================================

CREATE TABLE SURVEYS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  TITLE NVARCHAR(255) NOT NULL,
  DESCRIPTION NVARCHAR(MAX),
  TARGET_TYPE VARCHAR(30), -- STUDENT, TEACHER, PARENT, ALL
  CLASS_ID INT,
  COURSE_ID INT,
  START_DATE DATE,
  END_DATE DATE,
  IS_ACTIVE BIT DEFAULT 1,
  CREATED_BY INT NOT NULL,
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_SURVEYS_CLASSES FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID),
  CONSTRAINT FK_SURVEYS_COURSES FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID),
  CONSTRAINT FK_SURVEYS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

CREATE TABLE SURVEY_QUESTIONS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  SURVEY_ID INT NOT NULL,
  QUESTION_TEXT NVARCHAR(MAX) NOT NULL,
  QUESTION_TYPE VARCHAR(30) DEFAULT 'MULTIPLE_CHOICE', -- MULTIPLE_CHOICE, TEXT, RATING, YES_NO
  OPTIONS NVARCHAR(MAX), -- JSON STRING FOR MULTIPLE CHOICE OPTIONS
  IS_REQUIRED BIT DEFAULT 0,
  QUESTION_ORDER INT,
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_SURVEY_QUESTIONS_SURVEYS FOREIGN KEY (SURVEY_ID) REFERENCES SURVEYS(ID) ON DELETE CASCADE
);

CREATE TABLE SURVEY_RESPONSES (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  SURVEY_ID INT NOT NULL,
  QUESTION_ID INT NOT NULL,
  RESPONDENT_ID INT NOT NULL,
  ANSWER_TEXT NVARCHAR(MAX),
  ANSWER_RATING INT,
  SUBMITTED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_SURVEY_RESPONSES_SURVEYS FOREIGN KEY (SURVEY_ID) REFERENCES SURVEYS(ID),
  CONSTRAINT FK_SURVEY_RESPONSES_QUESTIONS FOREIGN KEY (QUESTION_ID) REFERENCES SURVEY_QUESTIONS(ID),
  CONSTRAINT FK_SURVEY_RESPONSES_USERS FOREIGN KEY (RESPONDENT_ID) REFERENCES USERS(ID)
);

-- =================================================================
-- BẢNG THÔNG BÁO & HỆ THỐNG
-- =================================================================

CREATE TABLE NEWS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  TITLE NVARCHAR(255) NOT NULL,
  EXCERPT NVARCHAR(500),
  CONTENT NVARCHAR(MAX),
  IMAGE_URL VARCHAR(500),
  TYPE VARCHAR(50) DEFAULT 'NEWS', -- NEWS, ANNOUNCEMENT, EVENT
  STATUS VARCHAR(20) DEFAULT 'DRAFT', -- DRAFT, PUBLISHED, ARCHIVED
  IS_FEATURED BIT DEFAULT 0,
  AUTHOR_ID INT NOT NULL,
  PUBLISHED_AT DATETIME2,
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  UPDATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_NEWS_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(ID)
);

CREATE TABLE NOTIFICATIONS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  USER_ID INT NOT NULL,
  TITLE NVARCHAR(255) NOT NULL,
  MESSAGE NVARCHAR(MAX),
  TYPE VARCHAR(30) DEFAULT 'INFO', -- INFO, SUCCESS, WARNING, ERROR
  IS_READ BIT DEFAULT 0,
  ACTION_LINK VARCHAR(500),
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_NOTIFICATIONS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- =================================================================
-- BẢNG TÀI CHÍNH - EXPENSES
-- =================================================================

CREATE TABLE EXPENSES (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  EXPENSE_CODE VARCHAR(50) UNIQUE,
  EXPENSE_DATE DATETIME2 NOT NULL,
  CATEGORY NVARCHAR(100) NOT NULL, -- Lương nhân viên, Tiền thuê nhà, Tiền điện, Tiền nước, Tiếp thị và quảng cáo, Trang thiết bị, Bảo trì, Khác
  AMOUNT DECIMAL(18,2) NOT NULL,
  DESCRIPTION NVARCHAR(500),
  PAYMENT_METHOD VARCHAR(50) DEFAULT 'BANK_TRANSFER', -- CASH, BANK_TRANSFER, CREDIT_CARD, CHECK
  APPROVED_BY VARCHAR(100),
  RECEIPT_NUMBER VARCHAR(50),
  NOTES NVARCHAR(MAX),
  CREATED_BY VARCHAR(100),
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  UPDATED_AT DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE ACTIVITY_LOGS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  USER_ID INT,
  ACTION VARCHAR(100) NOT NULL,
  ENTITY_TYPE VARCHAR(50),
  ENTITY_ID INT,
  DETAILS NVARCHAR(MAX),
  IP_ADDRESS VARCHAR(45),
  USER_AGENT NVARCHAR(500),
  CREATED_AT DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_ACTIVITY_LOGS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE SYSTEM_SETTINGS (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  SETTING_KEY VARCHAR(100) UNIQUE NOT NULL,
  SETTING_VALUE NVARCHAR(MAX),
  DESCRIPTION NVARCHAR(500),
  UPDATED_AT DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE BACKUP_HISTORY (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  BACKUP_NAME VARCHAR(255) NOT NULL,
  BACKUP_PATH VARCHAR(500),
  BACKUP_SIZE BIGINT,
  BACKUP_TYPE VARCHAR(20) DEFAULT 'FULL', -- FULL, INCREMENTAL
  STATUS VARCHAR(20) DEFAULT 'COMPLETED', -- IN_PROGRESS, COMPLETED, FAILED
  STARTED_AT DATETIME2 DEFAULT GETDATE(),
  COMPLETED_AT DATETIME2
);

-- =================================================================
-- INDEXES FOR PERFORMANCE
-- =================================================================

-- USERS AND AUTHENTICATION
CREATE INDEX IX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IX_USERS_ROLE_ID ON USERS(ROLE_ID);
CREATE INDEX IX_USERS_STATUS ON USERS(STATUS);

-- STUDENTS, TEACHERS, STAFF
CREATE INDEX IX_STUDENTS_USER_ID ON STUDENTS(USER_ID);
CREATE INDEX IX_STUDENTS_STUDENT_CODE ON STUDENTS(STUDENT_CODE);
CREATE INDEX IX_TEACHERS_USER_ID ON TEACHERS(USER_ID);
CREATE INDEX IX_TEACHERS_TEACHER_CODE ON TEACHERS(TEACHER_CODE);
CREATE INDEX IX_STAFF_USER_ID ON STAFF(USER_ID);

-- ACADEMIC
CREATE INDEX IX_COURSES_SUBJECT_ID ON COURSES(SUBJECT_ID);
CREATE INDEX IX_COURSES_IS_ACTIVE ON COURSES(IS_ACTIVE);
CREATE INDEX IX_CLASSES_COURSE_ID ON CLASSES(COURSE_ID);
CREATE INDEX IX_CLASSES_TEACHER_ID ON CLASSES(TEACHER_ID);
CREATE INDEX IX_CLASSES_STATUS ON CLASSES(STATUS);
CREATE INDEX IX_CLASS_SESSIONS_CLASS_ID ON CLASS_SESSIONS(CLASS_ID);

-- ENROLLMENTS AND ATTENDANCE
CREATE INDEX IX_ENROLLMENTS_CLASS_ID ON ENROLLMENTS(CLASS_ID);
CREATE INDEX IX_ENROLLMENTS_STUDENT_ID ON ENROLLMENTS(STUDENT_ID);
CREATE INDEX IX_ENROLLMENTS_STATUS ON ENROLLMENTS(STATUS);
CREATE INDEX IX_ATTENDANCE_SESSION_ID ON ATTENDANCE(SESSION_ID);
CREATE INDEX IX_ATTENDANCE_ENROLLMENT_ID ON ATTENDANCE(ENROLLMENT_ID);

-- ASSIGNMENTS AND SUBMISSIONS
CREATE INDEX IX_ASSIGNMENTS_CLASS_ID ON ASSIGNMENTS(CLASS_ID);
CREATE INDEX IX_SUBMISSIONS_ASSIGNMENT_ID ON SUBMISSIONS(ASSIGNMENT_ID);
CREATE INDEX IX_SUBMISSIONS_STUDENT_ID ON SUBMISSIONS(STUDENT_ID);

-- PAYMENTS
CREATE INDEX IX_PAYMENTS_ENROLLMENT_ID ON PAYMENTS(ENROLLMENT_ID);
CREATE INDEX IX_PAYMENTS_STATUS ON PAYMENTS(STATUS);

-- NEWS
CREATE INDEX IX_NEWS_TYPE ON NEWS(TYPE);
CREATE INDEX IX_NEWS_STATUS ON NEWS(STATUS);
CREATE INDEX IX_NEWS_AUTHOR_ID ON NEWS(AUTHOR_ID);
CREATE INDEX IX_NEWS_IS_FEATURED ON NEWS(IS_FEATURED);
CREATE INDEX IX_NEWS_PUBLISHED_AT ON NEWS(PUBLISHED_AT);

-- NOTIFICATIONS
CREATE INDEX IX_NOTIFICATIONS_USER_ID ON NOTIFICATIONS(USER_ID);
CREATE INDEX IX_NOTIFICATIONS_IS_READ ON NOTIFICATIONS(IS_READ);

GO

-- =================================================================
-- INSERT DEFAULT DATA - ROLES
-- =================================================================

SET IDENTITY_INSERT ROLES ON;

INSERT INTO ROLES (ID, CODE, NAME, DESCRIPTION) VALUES
(1, 'ADMIN', N'Quản trị viên', N'Quản trị hệ thống, có toàn quyền'),
(2, 'STAFF', N'Nhân viên', N'Nhân viên văn phòng, quản lý học vụ'),
(3, 'TEACHER', N'Giáo viên', N'Giảng dạy và quản lý lớp học'),
(4, 'STUDENT', N'Học sinh', N'Học viên tham gia khóa học');

SET IDENTITY_INSERT ROLES OFF;

GO
