-- =============================================
-- DMT EDUCATION SYSTEM - INSERT PAYMENTS FROM MOCK DATA
-- File: Insert_Payments_From_Mock.sql
-- Description: Import 15 payment transactions from paymentData.ts
-- =============================================

USE DMT_EDUCATION_SYSTEM;
GO

PRINT '============================================';
PRINT 'Inserting Payments from Mock Data';
PRINT '============================================';
PRINT '';

-- Get existing student and enrollment IDs
DECLARE @Student1_ID INT = (SELECT TOP 1 ID FROM STUDENTS WHERE STUDENT_CODE = 'HS2024001');
DECLARE @Student2_ID INT = (SELECT TOP 1 ID FROM STUDENTS WHERE STUDENT_CODE = 'HS2024002');
DECLARE @Student3_ID INT = (SELECT TOP 1 ID FROM STUDENTS WHERE STUDENT_CODE = 'HS2024003');
DECLARE @Student4_ID INT = (SELECT TOP 1 ID FROM STUDENTS WHERE STUDENT_CODE = 'HS2024004');
DECLARE @Student5_ID INT = (SELECT TOP 1 ID FROM STUDENTS WHERE STUDENT_CODE = 'HS2024005');
DECLARE @Student6_ID INT = (SELECT TOP 1 ID FROM STUDENTS WHERE STUDENT_CODE = 'HS2024006');
DECLARE @Student7_ID INT = (SELECT TOP 1 ID FROM STUDENTS WHERE STUDENT_CODE = 'HS2024007');
DECLARE @Student8_ID INT = (SELECT TOP 1 ID FROM STUDENTS WHERE STUDENT_CODE = 'HS2024008');

-- Get enrollment IDs (we'll use class enrollments as a proxy)
DECLARE @Enroll1_ID INT, @Enroll2_ID INT, @Enroll3_ID INT, @Enroll4_ID INT;
DECLARE @Enroll5_ID INT, @Enroll6_ID INT, @Enroll7_ID INT, @Enroll8_ID INT;

SELECT @Enroll1_ID = ID FROM ENROLLMENTS WHERE STUDENT_ID = @Student1_ID;
SELECT @Enroll2_ID = ID FROM ENROLLMENTS WHERE STUDENT_ID = @Student2_ID;
SELECT @Enroll3_ID = ID FROM ENROLLMENTS WHERE STUDENT_ID = @Student3_ID;
SELECT @Enroll4_ID = ID FROM ENROLLMENTS WHERE STUDENT_ID = @Student4_ID;
SELECT @Enroll5_ID = ID FROM ENROLLMENTS WHERE STUDENT_ID = @Student5_ID;
SELECT @Enroll6_ID = ID FROM ENROLLMENTS WHERE STUDENT_ID = @Student6_ID;
SELECT @Enroll7_ID = ID FROM ENROLLMENTS WHERE STUDENT_ID = @Student7_ID;
SELECT @Enroll8_ID = ID FROM ENROLLMENTS WHERE STUDENT_ID = @Student8_ID;

-- Create enrollments if they don't exist
IF @Enroll1_ID IS NULL
BEGIN
    INSERT INTO ENROLLMENTS (STUDENT_ID, CLASS_ID, ENROLLMENT_DATE, STATUS)
    VALUES (@Student1_ID, (SELECT TOP 1 ID FROM CLASSES WHERE STATUS = 'ACTIVE'), '2023-08-10', 'ACTIVE');
    SET @Enroll1_ID = SCOPE_IDENTITY();
END

IF @Enroll2_ID IS NULL
BEGIN
    INSERT INTO ENROLLMENTS (STUDENT_ID, CLASS_ID, ENROLLMENT_DATE, STATUS)
    VALUES (@Student2_ID, (SELECT TOP 1 ID FROM CLASSES WHERE STATUS = 'ACTIVE'), '2023-08-15', 'ACTIVE');
    SET @Enroll2_ID = SCOPE_IDENTITY();
END

IF @Enroll3_ID IS NULL
BEGIN
    INSERT INTO ENROLLMENTS (STUDENT_ID, CLASS_ID, ENROLLMENT_DATE, STATUS)
    VALUES (@Student3_ID, (SELECT TOP 1 ID FROM CLASSES WHERE STATUS = 'ACTIVE'), '2023-08-18', 'ACTIVE');
    SET @Enroll3_ID = SCOPE_IDENTITY();
END

IF @Enroll4_ID IS NULL
BEGIN
    INSERT INTO ENROLLMENTS (STUDENT_ID, CLASS_ID, ENROLLMENT_DATE, STATUS)
    VALUES (@Student4_ID, (SELECT TOP 1 ID FROM CLASSES WHERE STATUS = 'ACTIVE'), '2023-09-01', 'ACTIVE');
    SET @Enroll4_ID = SCOPE_IDENTITY();
END

IF @Enroll5_ID IS NULL
BEGIN
    INSERT INTO ENROLLMENTS (STUDENT_ID, CLASS_ID, ENROLLMENT_DATE, STATUS)
    VALUES (@Student5_ID, (SELECT TOP 1 ID FROM CLASSES WHERE STATUS = 'ACTIVE'), '2023-09-08', 'ACTIVE');
    SET @Enroll5_ID = SCOPE_IDENTITY();
END

IF @Enroll6_ID IS NULL
BEGIN
    INSERT INTO ENROLLMENTS (STUDENT_ID, CLASS_ID, ENROLLMENT_DATE, STATUS)
    VALUES (@Student6_ID, (SELECT TOP 1 ID FROM CLASSES WHERE STATUS = 'ACTIVE'), '2023-09-12', 'ACTIVE');
    SET @Enroll6_ID = SCOPE_IDENTITY();
END

IF @Enroll7_ID IS NULL
BEGIN
    INSERT INTO ENROLLMENTS (STUDENT_ID, CLASS_ID, ENROLLMENT_DATE, STATUS)
    VALUES (@Student7_ID, (SELECT TOP 1 ID FROM CLASSES WHERE STATUS = 'ACTIVE'), '2023-09-20', 'ACTIVE');
    SET @Enroll7_ID = SCOPE_IDENTITY();
END

IF @Enroll8_ID IS NULL
BEGIN
    INSERT INTO ENROLLMENTS (STUDENT_ID, CLASS_ID, ENROLLMENT_DATE, STATUS)
    VALUES (@Student8_ID, (SELECT TOP 1 ID FROM CLASSES WHERE STATUS = 'ACTIVE'), '2023-09-28', 'ACTIVE');
    SET @Enroll8_ID = SCOPE_IDENTITY();
END

-- Clear existing payments to avoid duplicates
DELETE FROM PAYMENTS WHERE PAYMENT_CODE LIKE 'PMT-23%';
PRINT 'Cleared existing mock payments';

-- Insert Payments
PRINT 'Inserting 15 payment transactions...';

-- PMT-23001
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23001',
    @Enroll1_ID,
    4500000,
    '2023-08-15',
    'BANK_TRANSFER',
    'COMPLETED',
    'R-2308-001',
    N'Thanh toán học phí kỳ 1 khóa Tiếng Anh nâng cao',
    'admin'
);

-- PMT-23002
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23002',
    @Enroll2_ID,
    7800000,
    '2023-08-17',
    'CASH',
    'COMPLETED',
    'R-2308-002',
    N'Thanh toán học phí đầy đủ khóa Luyện thi IELTS',
    'admin'
);

-- PMT-23003
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23003',
    @Enroll3_ID,
    3200000,
    '2023-08-20',
    'E_WALLET',
    'COMPLETED',
    'R-2308-003',
    N'Thanh toán học phí khóa Tiếng Anh giao tiếp qua MoMo',
    'staff-001'
);

-- PMT-23004
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23004',
    @Enroll4_ID,
    2500000,
    '2023-09-05',
    'BANK_TRANSFER',
    'PENDING',
    NULL,
    N'Đặt cọc học phí khóa Tiếng Anh cho trẻ em',
    'staff-002'
);

-- PMT-23005
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23005',
    @Enroll5_ID,
    4500000,
    '2023-09-10',
    'CREDIT_CARD',
    'FAILED',
    NULL,
    N'Thanh toán học phí qua thẻ - Giao dịch thất bại',
    'admin'
);

-- PMT-23006
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23006',
    @Enroll6_ID,
    5200000,
    '2023-09-15',
    'CASH',
    'COMPLETED',
    'R-2309-006',
    N'Thanh toán học phí đầy đủ khóa Luyện thi TOEIC',
    'staff-001'
);

-- PMT-23007
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23007',
    @Enroll7_ID,
    6000000,
    '2023-09-22',
    'BANK_TRANSFER',
    'COMPLETED',
    'R-2309-007',
    N'Thanh toán học phí khóa Tiếng Anh thương mại',
    'admin'
);

-- PMT-23008 - Refunded
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, PAYMENT_DETAILS, CREATED_BY)
VALUES (
    'PMT-23008',
    @Enroll3_ID,
    4800000,
    '2023-10-01',
    'CREDIT_CARD',
    'REFUNDED',
    'R-2310-008',
    N'Hoàn học phí do hủy đăng ký khóa học',
    'Refund to card ending 4321',
    'admin'
);

-- PMT-23009
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23009',
    @Enroll8_ID,
    7800000,
    '2023-10-08',
    'BANK_TRANSFER',
    'PENDING',
    NULL,
    N'Chờ xác nhận thanh toán học phí Luyện thi IELTS',
    'staff-002'
);

-- PMT-23010
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23010',
    @Enroll1_ID,
    5500000,
    '2023-10-12',
    'E_WALLET',
    'COMPLETED',
    'R-2310-010',
    N'Thanh toán học phí khóa Tiếng Anh chuyên ngành IT qua ZaloPay',
    'staff-001'
);

-- PMT-23011
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23011',
    @Enroll2_ID,
    5200000,
    '2023-10-15',
    'CASH',
    'COMPLETED',
    'R-2310-011',
    N'Thanh toán học phí khóa Luyện thi TOEIC',
    'admin'
);

-- PMT-23012
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23012',
    @Enroll4_ID,
    4500000,
    '2023-10-20',
    'BANK_TRANSFER',
    'PENDING',
    NULL,
    N'Đặt cọc học phí khóa Tiếng Anh nâng cao',
    'staff-002'
);

-- PMT-23013
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23013',
    @Enroll5_ID,
    6000000,
    '2023-10-25',
    'E_WALLET',
    'FAILED',
    NULL,
    N'Thanh toán học phí qua ví MoMo - Giao dịch thất bại',
    'admin'
);

-- PMT-23014
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23014',
    @Enroll6_ID,
    3200000,
    '2023-10-28',
    'CASH',
    'COMPLETED',
    'R-2310-014',
    N'Thanh toán học phí khóa Tiếng Anh giao tiếp',
    'staff-001'
);

-- PMT-23015
INSERT INTO PAYMENTS (PAYMENT_CODE, ENROLLMENT_ID, AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, STATUS, RECEIPT_NUMBER, DESCRIPTION, CREATED_BY)
VALUES (
    'PMT-23015',
    @Enroll7_ID,
    2500000,
    '2023-11-02',
    'CREDIT_CARD',
    'COMPLETED',
    'R-2311-015',
    N'Thanh toán học phí khóa Tiếng Anh cho trẻ em qua thẻ tín dụng',
    'admin'
);

-- Verify inserted data
PRINT '';
PRINT 'Verification:';
SELECT 
    COUNT(*) as total_payments,
    SUM(CASE WHEN STATUS = 'COMPLETED' THEN 1 ELSE 0 END) as completed,
    SUM(CASE WHEN STATUS = 'PENDING' THEN 1 ELSE 0 END) as pending,
    SUM(CASE WHEN STATUS = 'FAILED' THEN 1 ELSE 0 END) as failed,
    SUM(CASE WHEN STATUS = 'REFUNDED' THEN 1 ELSE 0 END) as refunded,
    SUM(AMOUNT) as total_amount
FROM PAYMENTS
WHERE PAYMENT_CODE LIKE 'PMT-23%';

PRINT '';
PRINT 'Sample payments:';
SELECT TOP 5
    PAYMENT_CODE,
    AMOUNT,
    PAYMENT_DATE,
    PAYMENT_METHOD,
    STATUS,
    RECEIPT_NUMBER
FROM PAYMENTS
WHERE PAYMENT_CODE LIKE 'PMT-23%'
ORDER BY PAYMENT_DATE DESC;

PRINT '';
PRINT '============================================';
PRINT 'Payments import completed successfully!';
PRINT '============================================';

GO
